### ISSUE TITLE
Any guidelines to run the code to generate data?

### ISSUE THREAD

**Issue by sustcsonglin** [konstantinosKokos/metaclass-cfg#12]

**Comment by gijswijnholds** [comment]
The simplest would be to follow the code in example_cluster.py.
This repo was part of our ACL paper which describes the whole setup (see https://github.com/gijswijnholds/discontinuous-probing), which combines both an MCFG with linkings between verbs and nouns.

You should follow a number of steps (using example_cluster.py as a running example):

1. Define your non-terminal symbols (lines 120-141)
2. Give the actual MCFG in annotated rule format (144-229). The first element of a rule is a pair of a non-terminal symbol and its unfolding, the second element has a dict to link verbs to nouns in the current rule, and then a tuple of bools indicating whether a symbol should 'inherit' a noun-linking. This is only relevant if you're also interested in generating the verb-noun linkings. The last element of a rule is a tuple of lists of pairs that indicate how the elements of the rhs non-terminals should be rewritten to constitute the lhs non-terminal (Ex: A(xy,z) -> B(x, z) C(y) would be annotated ([(0,0), (1,0)], [(0,1)]) ).
3. Define the constants for filling in words for the non-terminals (e.g. nouns, verbs etc). This is done in the set_constants method and in setup_grammar. This will lead you to our Lexicon code. But here you should code up your own lexicon, depending on what you want to generate.
4. Generate the grammar!

Hope this helps,
